language = "C"
include_version = true
pragma_once = true

[export]
item_types = ["constants", "enums", "structs", "unions", "typedefs", "opaque"]
include = [
  "CPeakOptions",
  "Buf",
  "MSUTILS_ABI_VERSION",
]

[parse]
parse_deps = false
